import type { CampaignRevisionView, ContractEnvelope, GenerationAction, GenerationContext, GenerationEvent, GenerationView, OperationRequest, ProposalApprovalResult, ProposalView, ProviderReadiness, RecordView } from "../contracts/v2";

export const frontendCapabilities = ["provider_readiness", "campaign_list", "campaign_read", "atlas_read", "retrieval_preview", "draft_read", "live_observe", "proposal_read", "revision_read"] as const;
export type FrontendCapability = (typeof frontendCapabilities)[number];
export interface ContractTransport { send<Response extends ContractEnvelope<string>>(capability: FrontendCapability, request: ContractEnvelope<string>, signal?: AbortSignal): Promise<Response>; submit<Response extends ContractEnvelope<string>>(request: OperationRequest, signal?: AbortSignal): Promise<Response>; }
export class ContractClient { public constructor(private readonly transport: ContractTransport) {} public read<Response extends ContractEnvelope<string>>(capability: FrontendCapability, request: ContractEnvelope<string>, signal?: AbortSignal): Promise<Response> { if (request.contract_version !== 2) throw new Error("unsupported_contract_version"); return this.transport.send<Response>(capability, request, signal); } public submit<Response extends ContractEnvelope<string>>(request: OperationRequest, signal?: AbortSignal): Promise<Response> { if (request.contract_version !== 2) throw new Error("unsupported_contract_version"); return this.transport.submit<Response>(request, signal); } }
export class ApiError extends Error { public constructor(public readonly status: number, public readonly code: string) { super(code); } }
export interface SliceApi { readiness(): Promise<ProviderReadiness>; consent(identityDigest: string, retryKey: string): Promise<ProviderReadiness>; createCampaign(name: string, campaignId: string, retryKey: string): Promise<CampaignRevisionView>; readRevision(campaignId: string, revisionId: string): Promise<CampaignRevisionView>; readRecord(campaignId: string, revisionId: string, recordId: string): Promise<RecordView>; startGeneration(campaignId: string, revisionId: string, action: GenerationAction, prompt: string, generationId: string, context: GenerationContext, sessionId?: string): Promise<GenerationView>; resumeGeneration(generationId: string, after: number): Promise<GenerationEvent[]>; readGeneration(generationId: string): Promise<GenerationView>; createProposal(generation: GenerationView, subjectId: string, proposalId: string, retryKey: string): Promise<ProposalView>; correctProposal(proposal: ProposalView, afterContent: string, retryKey: string): Promise<ProposalView>; rejectProposal(proposal: ProposalView, retryKey: string): Promise<ProposalView>; approveProposal(proposal: ProposalView, expectedHead: string, retryKey: string): Promise<ProposalApprovalResult>; }

const canonical = (value: unknown): string => { if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`; if (value !== null && typeof value === "object") return `{${Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => `${JSON.stringify(key)}:${canonical(item)}`).join(",")}}`; return JSON.stringify(value); };
async function sha256(value: string): Promise<string> { const bytes = new TextEncoder().encode(value); return [...new Uint8Array(await crypto.subtle.digest("SHA-256", bytes))].map((part) => part.toString(16).padStart(2, "0")).join(""); }
async function digest(value: unknown): Promise<string> { return sha256(canonical(value)); }
export async function recordGenerationContext(record: RecordView): Promise<GenerationContext> { return { scope: "record", record_id: record.record_id, content_digest: await sha256(record.content.replace(/\r\n/g, "\n").replace(/\r/g, "\n")) }; }
let nextId = 0;
let csrfToken = "";
export function browserId(prefix: string): string { nextId += 1; return `${prefix}_${Date.now().toString(36)}_${nextId}`; }
async function requestJson<T>(path: string, init?: RequestInit): Promise<T> { const response = await fetch(`/api/v1${path}`, { ...init, headers: { Accept: "application/json", "Content-Type": "application/json", ...(init?.method === "POST" && csrfToken ? { "X-CSRF-Token": csrfToken } : {}), ...init?.headers } }); csrfToken = response.headers.get("X-CSRF-Token") ?? csrfToken; const body = await response.json().catch(() => null) as { error?: { code?: string } } | null; if (!response.ok) throw new ApiError(response.status, body?.error?.code ?? "request_failed"); return body as T; }
function operation(name: OperationRequest["operation"], retryKey: string, payloadDigest: string, expectedRevision: string | null, subjectId?: string, intentDigest?: string): OperationRequest { return { contract_name: "operation_request", contract_version: 2, request_id: browserId("request"), operation: name, idempotency_key: retryKey, payload_digest: payloadDigest, expected_revision: expectedRevision, expected_workflow_version: null, ...(subjectId ? { subject_id: subjectId } : {}), ...(intentDigest ? { intent_digest: intentDigest } : {}) }; }

export const httpSliceApi: SliceApi = {
  readiness: () => requestJson("/provider/readiness"),
  async consent(identityDigest, retryKey) { const input = { explicit: true, consent_identity_digest: identityDigest }; return requestJson("/provider/consent", { method: "POST", body: JSON.stringify({ contract_name: "provider_consent_request", contract_version: 2, operation_request: operation("provider_consent", retryKey, await digest(input), null), input }) }); },
  async createCampaign(name, campaignId, retryKey) { const input = { campaign_id: campaignId, campaign_name: name, adapter_id: "mothership" }; return requestJson("/campaigns", { method: "POST", body: JSON.stringify({ contract_name: "campaign_create_request", contract_version: 2, operation_request: operation("campaign_create", retryKey, await digest(input), null), input }) }); },
  readRevision: (campaignId, revisionId) => requestJson(`/campaigns/${campaignId}/revisions/${revisionId}`),
  readRecord: (campaignId, revisionId, recordId) => requestJson(`/campaigns/${campaignId}/revisions/${revisionId}/records/${recordId}`),
  startGeneration: (campaignId, revisionId, action, prompt, generationId, context, sessionId) => requestJson(`/campaigns/${campaignId}/revisions/${revisionId}/generations`, { method: "POST", body: JSON.stringify({ contract_name: "generation_start_request", contract_version: 2, generation_id: generationId, campaign_id: campaignId, source_revision: revisionId, action, prompt, context, ...(sessionId ? { session_id: sessionId } : {}) }) }),
  async resumeGeneration(generationId, after) { const response = await fetch(`/api/v1/generations/${generationId}/events?after=${after}`, { headers: { Accept: "text/event-stream" } }); if (!response.ok) { const body = await response.json().catch(() => null) as { error?: { code?: string } } | null; throw new ApiError(response.status, body?.error?.code ?? "stream_failed"); } const text = await response.text(); return text.split(/\r?\n\r?\n/).flatMap((frame) => { const data = frame.split(/\r?\n/).find((line) => line.startsWith("data: ")); return data ? [JSON.parse(data.slice(6)) as GenerationEvent] : []; }); },
  readGeneration: (generationId) => requestJson(`/generations/${generationId}`),
  async createProposal(generation, subjectId, proposalId, retryKey) { const bare = { generation_id: generation.generation_id, proposal_id: proposalId, campaign_id: generation.campaign_id, source_revision: generation.source_revision, base_revision: generation.source_revision, source_set_digest: generation.source_set_digest, terminal_draft_digest: generation.terminal_content_digest!, subject_id: subjectId }; return requestJson(`/generations/${generation.generation_id}/proposals`, { method: "POST", body: JSON.stringify({ contract_name: "proposal_create_request", contract_version: 2, request_id: browserId("request"), idempotency_key: retryKey, payload_digest: await digest(bare), ...bare }) }); },
  async correctProposal(proposal, afterContent, retryKey) { const change = proposal.exact_diff[0]; const bare = { proposal_id: proposal.proposal_id, proposal_version: proposal.proposal_version, source_revision: proposal.source_revision, base_revision: proposal.base_revision, change_id: change.change_id, subject_id: change.subject_id, after_content: afterContent }; return requestJson(`/proposals/${proposal.proposal_id}/versions/${proposal.proposal_version}/corrections`, { method: "POST", body: JSON.stringify({ contract_name: "proposal_correction_request", contract_version: 2, operation_request: operation("proposal_correct", retryKey, await digest(bare), proposal.base_revision, proposal.proposal_id), ...bare }) }); },
  async rejectProposal(proposal, retryKey) { const bare = { proposal_id: proposal.proposal_id, proposal_version: proposal.proposal_version, source_revision: proposal.source_revision, base_revision: proposal.base_revision }; return requestJson(`/proposals/${proposal.proposal_id}/versions/${proposal.proposal_version}/rejection`, { method: "POST", body: JSON.stringify({ contract_name: "proposal_rejection_request", contract_version: 2, operation_request: operation("proposal_reject", retryKey, await digest(bare), proposal.base_revision, proposal.proposal_id), ...bare }) }); },
  async approveProposal(proposal, expectedHead, retryKey) {
    const bare = { proposal_id: proposal.proposal_id, proposal_version: proposal.proposal_version, source_revision: proposal.source_revision, base_revision: proposal.base_revision, expected_campaign_head: expectedHead, diff_digest: proposal.diff_digest, proposal_payload_digest: proposal.proposal_payload_digest, warden_confirmed: true };
    const response = await fetch(`/api/v1/proposals/${proposal.proposal_id}/versions/${proposal.proposal_version}/approval`, { method: "POST", headers: { Accept: "application/json", "Content-Type": "application/json", "X-CSRF-Token": csrfToken }, body: JSON.stringify({ contract_name: "proposal_approval_request", contract_version: 2, operation_request: operation("proposal_approve", retryKey, await digest(bare), expectedHead, proposal.proposal_id, proposal.diff_digest), ...bare }) });
    const body = await response.json() as ProposalApprovalResult | { error?: { code?: string } };
    if (response.ok || (response.status === 409 && "contract_name" in body && body.contract_name === "proposal_approval_result")) return body as ProposalApprovalResult;
    throw new ApiError(response.status, "error" in body ? body.error?.code ?? "request_failed" : "request_failed");
  },
};
