from pathlib import Path
from tempfile import TemporaryDirectory
from contextlib import redirect_stdout
from io import StringIO
import json
import subprocess
import sys
import unittest
from warden_drydock import __version__
from warden_drydock import standalone
from warden_drydock.cli import main
from warden_drydock.core.generator import init_campaign
from warden_drydock.core.validation import validate_campaign
from warden_drydock.core.context import build_context
from warden_drydock.core.upgrade import upgrade_campaign
from warden_drydock.standalone import create_entity

class GeneratorTest(unittest.TestCase):
    def test_mothership_campaign_generation(self):
        with TemporaryDirectory() as tmp:
            root=Path(tmp)/'campaign'
            init_campaign(root,name='Test Campaign',adapter='mothership')
            self.assertTrue((root/'.drydock.json').exists())
            manifest=json.loads((root/'.drydock.json').read_text())
            self.assertEqual(manifest['framework_version'],__version__)
            adapter=json.loads((root/'00-drydock'/'adapter.json').read_text())
            self.assertEqual(manifest['adapter'],adapter['adapter'])
            self.assertEqual(manifest['adapter_version'],adapter['adapter_version'])
            lock=json.loads((root/'.drydock-lock.json').read_text())
            self.assertEqual(lock['schema_version'],1)
            self.assertEqual(lock['adapter_version'],adapter['adapter_version'])
            self.assertEqual(
                lock['files']['01-campaign/campaign-overview.md']['ownership'],
                'campaign',
            )
            self.assertEqual(
                lock['files']['00-drydock/ai-context.md']['ownership'],
                'generated',
            )
            self.assertEqual(lock['files']['templates/npc.md']['ownership'],'shared')
            self.assertIn('Test Campaign',(root/'README.md').read_text())
            self.assertTrue((root/'templates'/'npc.md').exists())
            self.assertEqual(
                (root/'scripts'/'drydock.py').read_text(encoding='utf-8'),
                Path(standalone.__file__).read_text(encoding='utf-8'),
            )
            self.assertEqual(validate_campaign(root),0)
            self.assertTrue(build_context(root).exists())

    def test_bootstrap_creates_context_and_validates_standalone(self):
        with TemporaryDirectory() as tmp:
            root=Path(tmp)/'campaign'
            self.assertEqual(main(['bootstrap',str(root),'--name','Test Campaign']),0)
            context=(root/'00-drydock'/'ai-context.md').read_text(encoding='utf-8')
            self.assertIn('Generated by Warden Drydock',context)
            self.assertIn('Mothership System Principles',context)
            result=subprocess.run(
                [sys.executable,str(root/'scripts'/'drydock.py'),'validate'],
                cwd=root,
                capture_output=True,
                text=True,
                check=False,
            )
            self.assertEqual(result.returncode,0,result.stdout+result.stderr)

    def test_bootstrap_refuses_non_empty_directory(self):
        with TemporaryDirectory() as tmp:
            root=Path(tmp)/'campaign'
            root.mkdir()
            existing=root/'notes.md'
            existing.write_text('user content',encoding='utf-8')
            with self.assertRaises(SystemExit):
                main(['bootstrap',str(root),'--name','Test Campaign'])
            self.assertEqual(existing.read_text(encoding='utf-8'),'user content')

    def test_context_uses_only_approved_sessions_and_is_stable(self):
        with TemporaryDirectory() as tmp:
            root=Path(tmp)/'campaign'
            init_campaign(root,name='Test Campaign',adapter='mothership')
            logs=root/'12-sessions'/'logs'
            logs.mkdir(parents=True,exist_ok=True)
            (logs/'001-approved.md').write_text(
                '---\nid: session-001\ntype: session\nstatus: canon\n---\n\n# Approved Event\n',
                encoding='utf-8',
            )
            (logs/'999-draft.md').write_text(
                '---\nid: session-999\ntype: session\nstatus: draft\n---\n\n# Unapproved Idea\n',
                encoding='utf-8',
            )
            output=build_context(root)
            first=output.read_text(encoding='utf-8')
            build_context(root)
            self.assertEqual(output.read_text(encoding='utf-8'),first)
            self.assertIn('Approved Event',first)
            self.assertNotIn('Unapproved Idea',first)

    def test_standalone_validator_detects_merge_conflicts(self):
        with TemporaryDirectory() as tmp:
            root=Path(tmp)/'campaign'
            init_campaign(root,name='Test Campaign',adapter='mothership')
            (root/'conflict.md').write_text('<<<<<<< ours\n=======\n>>>>>>> theirs\n')
            result=subprocess.run(
                [sys.executable,str(root/'scripts'/'drydock.py'),'validate'],
                cwd=root,
                capture_output=True,
                text=True,
                check=False,
            )
            self.assertEqual(result.returncode,1)
            self.assertIn('merge conflict marker',result.stdout)

    def test_upgrade_previews_then_restores_missing_managed_file(self):
        with TemporaryDirectory() as tmp:
            root=Path(tmp)/'campaign'
            init_campaign(root,name='Test Campaign',adapter='mothership')
            readme=root/'README.md'
            readme.unlink()
            preview=StringIO()
            with redirect_stdout(preview):
                self.assertEqual(upgrade_campaign(root),0)
            self.assertFalse(readme.exists())
            self.assertIn('Would update: README.md',preview.getvalue())
            self.assertEqual(upgrade_campaign(root,apply=True),0)
            self.assertTrue(readme.exists())

    def test_upgrade_blocks_modified_managed_file_and_preserves_campaign(self):
        with TemporaryDirectory() as tmp:
            root=Path(tmp)/'campaign'
            init_campaign(root,name='Test Campaign',adapter='mothership')
            readme=root/'README.md'
            readme.write_text('local customization',encoding='utf-8')
            campaign=root/'01-campaign'/'campaign-overview.md'
            original=campaign.read_text(encoding='utf-8')
            # Simulate a framework update by changing the recorded baseline.
            lock=json.loads((root/'.drydock-lock.json').read_text())
            lock['files']['README.md']['sha256']='obsolete-baseline'
            (root/'.drydock-lock.json').write_text(json.dumps(lock),encoding='utf-8')
            output=StringIO()
            with redirect_stdout(output):
                self.assertEqual(upgrade_campaign(root,apply=True),1)
            self.assertEqual(readme.read_text(encoding='utf-8'),'local customization')
            self.assertEqual(campaign.read_text(encoding='utf-8'),original)
            self.assertIn('CONFLICT: README.md',output.getvalue())

    def test_adapter_declares_and_creates_campaign_entities(self):
        with TemporaryDirectory() as tmp:
            root=Path(tmp)/'campaign'
            init_campaign(root,name='Test Campaign',adapter='mothership')
            entity=create_entity(root,'npc','npc-ripley','Ripley')
            text=entity.read_text(encoding='utf-8')
            self.assertEqual(entity.relative_to(root).as_posix(),'05-npcs/npc-ripley.md')
            self.assertIn('id: npc-ripley',text)
            self.assertIn('ownership: campaign',text)
            self.assertIn('name: "Ripley"',text)
            self.assertIn('# Ripley',text)
            self.assertEqual(validate_campaign(root),0)
            with self.assertRaises(SystemExit):
                create_entity(root,'npc','npc-ripley','Duplicate')

    def test_semantic_validation_rejects_missing_adapter_fields(self):
        with TemporaryDirectory() as tmp:
            root=Path(tmp)/'campaign'
            init_campaign(root,name='Test Campaign',adapter='mothership')
            entity=create_entity(root,'faction','faction-company','The Company')
            entity.write_text(
                entity.read_text(encoding='utf-8').replace('status: idea\n',''),
                encoding='utf-8',
            )
            output=StringIO()
            with redirect_stdout(output):
                self.assertEqual(validate_campaign(root),1)
            self.assertIn('missing required field status',output.getvalue())

    def test_validation_rejects_inconsistent_adapter_metadata(self):
        with TemporaryDirectory() as tmp:
            root=Path(tmp)/'campaign'
            init_campaign(root,name='Test Campaign',adapter='mothership')
            adapter_path=root/'00-drydock'/'adapter.json'
            adapter=json.loads(adapter_path.read_text(encoding='utf-8'))
            adapter['adapter_version']='9.9.9'
            adapter_path.write_text(json.dumps(adapter),encoding='utf-8')
            output=StringIO()
            with redirect_stdout(output):
                self.assertEqual(validate_campaign(root),1)
            self.assertIn(
                'adapter_version does not match adapter.json', output.getvalue()
            )

    def test_adapter_visibility_rules_are_declarative(self):
        with TemporaryDirectory() as tmp:
            root=Path(tmp)/'campaign'
            init_campaign(root,name='Test Campaign',adapter='mothership')
            entity=create_entity(root,'npc','npc-leak','Leak')
            entity.write_text(
                entity.read_text(encoding='utf-8').replace(
                    'visibility: warden', 'visibility: players'
                ),
                encoding='utf-8',
            )
            output=StringIO()
            with redirect_stdout(output):
                self.assertEqual(validate_campaign(root),1)
            result=output.getvalue()
            self.assertIn('visibility must be warden for npc',result)
            self.assertIn(
                'forbidden field combination visibility=players, warden_only=true',
                result,
            )

    def test_adapter_validation_rejects_malformed_declarations(self):
        with TemporaryDirectory() as tmp:
            root=Path(tmp)/'campaign'
            init_campaign(root,name='Test Campaign',adapter='mothership')
            adapter_path=root/'00-drydock'/'adapter.json'
            adapter=json.loads(adapter_path.read_text(encoding='utf-8'))
            adapter['validation']['field_values']='not-an-object'
            adapter_path.write_text(json.dumps(adapter),encoding='utf-8')
            output=StringIO()
            with redirect_stdout(output):
                self.assertEqual(validate_campaign(root),1)
            self.assertIn(
                'validation.field_values must map fields', output.getvalue()
            )

    def test_legacy_paths_warn_and_upgrade_never_moves_campaign_files(self):
        with TemporaryDirectory() as tmp:
            root=Path(tmp)/'campaign'
            init_campaign(root,name='Test Campaign',adapter='mothership')
            legacy_files={
                '06-factions/old-faction.md': '# Old faction\n',
                '05-characters/npcs/old-npc.md': '# Old NPC\n',
                '10-adventures/old-adventure.md': '# Old adventure\n',
            }
            for relative,content in legacy_files.items():
                path=root/relative
                path.parent.mkdir(parents=True,exist_ok=True)
                path.write_text(content,encoding='utf-8')
            output=StringIO()
            with redirect_stdout(output):
                self.assertEqual(validate_campaign(root),0)
            self.assertEqual(output.getvalue().count('legacy adapter path'),3)
            (root/'README.md').unlink()
            self.assertEqual(upgrade_campaign(root,apply=True),0)
            for relative,content in legacy_files.items():
                self.assertEqual((root/relative).read_text(encoding='utf-8'),content)
            self.assertFalse((root/'04-factions'/'old-faction.md').exists())
            self.assertFalse((root/'05-npcs'/'old-npc.md').exists())
            self.assertFalse(
                (root/'10-adventures'/'available'/'old-adventure.md').exists()
            )

    def _assert_narrative_record(self, text):
        forbidden={'strength:','speed:','intellect:','combat:','sanity:','fear:','body:','armor:','wounds:'}
        lowered=text.lower()
        self.assertTrue(forbidden.isdisjoint(lowered.splitlines()))
        self.assertIn('visibility: warden',lowered)
        self.assertIn('warden_only: true',lowered)

    def _assert_world_record(self, text):
        lowered=text.lower()
        self.assertNotIn('armor:',lowered)
        self.assertNotIn('wounds:',lowered)
        self.assertNotIn('combat:',lowered)

    def _assert_mystery_record(self, text):
        self.assertIn('## Warden truth',text)
        self.assertIn('player',text.lower())

    def _assert_session_record(self, text):
        self.assertIn('visibility: warden',text)
        self.assertIn('warden_only: true',text)

    def _assert_session_log_content(self, text):
        self.assertIn('## Unconfirmed beliefs and interpretations',text)
        self.assertIn('## Canon updates requiring review',text)

    def test_record_families_create_at_canonical_paths_and_validate(self):
        cases=(
            # Canonical mothership paths.
            ('faction','04-factions/faction-test.md','Test',()),
            ('npc','05-npcs/npc-test.md','Test',()),
            ('adventure','10-adventures/available/adventure-test.md','Test',()),
            ('session','12-sessions/logs/session-test.md','Test',()),
            # Narrative-only people records.
            ('character','02-players/characters/character-ripley.md','Character',(self._assert_narrative_record,)),
            ('npc','05-npcs/npc-mu-th-ur.md','Npc',(self._assert_narrative_record,)),
            ('faction','04-factions/faction-company.md','Faction',(self._assert_narrative_record,)),
            # World records.
            ('system','03-world/systems/system-ypsilon.md','System',(self._assert_world_record,)),
            ('location','03-world/locations/location-station.md','Location',(self._assert_world_record,)),
            ('creature','06-creatures/creature-signal.md','Creature',(self._assert_world_record,)),
            ('ship','07-ships/ship-prospero.md','Ship',(self._assert_world_record,)),
            ('item','08-items/item-sample.md','Item',(self._assert_world_record,)),
            # Mystery records.
            ('clue','09-mysteries/clues/clue-signal.md','Clue',(self._assert_mystery_record,)),
            ('false-belief','09-mysteries/false-beliefs/false-belief-rescue.md','False-Belief',(self._assert_mystery_record,)),
            ('revelation','09-mysteries/revelations/revelation-origin.md','Revelation',(self._assert_mystery_record,)),
            ('adventure','10-adventures/available/adventure-derelict.md','Adventure',(self._assert_mystery_record,)),
            # Campaign-engine records.
            ('clock','11-campaign-engine/clocks/clock-decay.md','Clock',()),
            ('consequence','11-campaign-engine/consequences/consequence-loss.md','Consequence',()),
            ('faction-turn','11-campaign-engine/faction-turns/faction-turn-001.md','Faction-Turn',()),
            ('random-table','14-random-tables/random-table-signals.md','Random-Table',()),
            # Session lifecycle records.
            ('session-prep','12-sessions/preparation/session-prep-001.md','Session 001',(self._assert_session_record,)),
            ('session','12-sessions/logs/session-001.md','Session 001',(self._assert_session_record,self._assert_session_log_content)),
            ('debrief','12-sessions/debriefs/debrief-001.md','Session 001',(self._assert_session_record,)),
        )
        with TemporaryDirectory() as tmp:
            root=Path(tmp)/'campaign'
            init_campaign(root,name='Test Campaign',adapter='mothership')
            for kind,relative,name,checks in cases:
                with self.subTest(kind=kind):
                    created=create_entity(root,kind,Path(relative).stem,name)
                    self.assertEqual(created.relative_to(root).as_posix(),relative)
                    text=created.read_text(encoding='utf-8')
                    for check in checks:
                        check(text)
            self.assertEqual(validate_campaign(root),0)

    def test_player_handout_enforces_adapter_secrecy_contract(self):
        with TemporaryDirectory() as tmp:
            root=Path(tmp)/'campaign'
            init_campaign(root,name='Test Campaign',adapter='mothership')
            handout=create_entity(root,'handout','handout-distress','Distress Call')
            self.assertEqual(handout.relative_to(root).as_posix(),'13-handouts/handout-distress.md')
            text=handout.read_text(encoding='utf-8')
            self.assertIn('visibility: players',text)
            self.assertIn('warden_only: false',text)
            output=StringIO()
            with redirect_stdout(output):
                self.assertEqual(validate_campaign(root),1)
            self.assertIn('field audience must not be empty',output.getvalue())
            handout.write_text(text.replace('audience: ""','audience: "all players"'),encoding='utf-8')
            self.assertEqual(validate_campaign(root),0)
            handout.write_text(handout.read_text(encoding='utf-8')+'\n## Warden truth\nLeak\n',encoding='utf-8')
            output=StringIO()
            with redirect_stdout(output):
                self.assertEqual(validate_campaign(root),1)
            self.assertIn('forbidden heading Warden truth',output.getvalue())

    def test_player_visibility_cannot_be_warden_only(self):
        with TemporaryDirectory() as tmp:
            root=Path(tmp)/'campaign'
            init_campaign(root,name='Test Campaign',adapter='mothership')
            handout=create_entity(root,'handout','handout-unsafe','Unsafe')
            handout.write_text(handout.read_text(encoding='utf-8').replace('warden_only: false','warden_only: true'),encoding='utf-8')
            output=StringIO()
            with redirect_stdout(output):
                self.assertEqual(validate_campaign(root),1)
            self.assertIn('forbidden field combination',output.getvalue())

    def test_mothership_workflow_guides_are_packaged_and_command_driven(self):
        guides=[
            'campaign-inception.md','situation-design.md','mystery-design.md',
            'session-preparation.md','debrief-workflow.md',
            'faction-turn-workflow.md','world-state.md',
            'canon-and-revelation.md','handout-safety.md',
        ]
        with TemporaryDirectory() as tmp:
            root=Path(tmp)/'campaign'
            init_campaign(root,name='Test Campaign',adapter='mothership')
            for guide in guides:
                text=(root/'docs'/guide).read_text(encoding='utf-8')
                self.assertIn('python scripts/drydock.py',text)
                self.assertTrue('review' in text.lower() or 'warden' in text.lower())
            principles=(root/'00-drydock/system-principles.md').read_text(encoding='utf-8')
            self.assertIn('narrative records',principles)
            self.assertIn('provisional',principles)

    def test_complete_mothership_registry_contract(self):
        expected={
            'character':'02-players/characters/{id}.md','location':'03-world/locations/{id}.md',
            'system':'03-world/systems/{id}.md','faction':'04-factions/{id}.md',
            'npc':'05-npcs/{id}.md','creature':'06-creatures/{id}.md',
            'ship':'07-ships/{id}.md','item':'08-items/{id}.md',
            'clue':'09-mysteries/clues/{id}.md','false-belief':'09-mysteries/false-beliefs/{id}.md',
            'revelation':'09-mysteries/revelations/{id}.md','adventure':'10-adventures/available/{id}.md',
            'clock':'11-campaign-engine/clocks/{id}.md','consequence':'11-campaign-engine/consequences/{id}.md',
            'faction-turn':'11-campaign-engine/faction-turns/{id}.md','session-prep':'12-sessions/preparation/{id}.md',
            'session':'12-sessions/logs/{id}.md','debrief':'12-sessions/debriefs/{id}.md',
            'handout':'13-handouts/{id}.md','random-table':'14-random-tables/{id}.md',
        }
        with TemporaryDirectory() as tmp:
            root=Path(tmp)/'campaign';init_campaign(root,name='Test',adapter='mothership')
            config=json.loads((root/'00-drydock/adapter.json').read_text(encoding='utf-8'))
            self.assertEqual(config['adapter_version'],'0.2.0')
            self.assertEqual(set(config['entity_types']),set(expected))
            forbidden=('strength:','speed:','intellect:','combat:','sanity:','fear:','body:','armor:','wounds:')
            for kind,destination in expected.items():
                rule=config['entity_types'][kind]
                self.assertEqual(rule['destination'],destination)
                template=root/rule['template']
                self.assertTrue(template.is_file())
                lower=template.read_text(encoding='utf-8').lower()
                self.assertFalse(any(field in lower for field in forbidden))
                self.assertIn('## summary', lower)
                self.assertIn('## current state', lower)
                self.assertIn('## connections', lower)

    def test_connections_generate_backlinks_and_budgeted_context(self):
        with TemporaryDirectory() as tmp:
            root=Path(tmp)/'campaign';init_campaign(root,name='Test',adapter='mothership')
            npc=create_entity(root,'npc','npc-ripley','Ripley')
            faction=create_entity(root,'faction','faction-company','The Company')
            npc.write_text(npc.read_text(encoding='utf-8').replace(
                '<!-- - `relationship` → [[target-id|Readable Name]] (`current`) — One concise sentence of context. -->',
                '- `works-for` → [[faction-company|The Company]] (`current`) — Handles salvage contracts.'
            ),encoding='utf-8')
            self.assertEqual(standalone.validate_campaign(root),0)
            entity_index,connection_index=standalone.build_indexes(root)
            self.assertIn('works-for [[faction-company]]',entity_index.read_text(encoding='utf-8'))
            self.assertIn('backlink `works-for` ← [[npc-ripley]]',connection_index.read_text(encoding='utf-8'))
            context=standalone.build_context(root,focus='npc-ripley',depth=1,max_records=1)
            text=context.read_text(encoding='utf-8')
            self.assertIn('Ripley (`npc-ripley`)',text)
            self.assertIn('Omitted 1 record(s)',text)

            shown=StringIO()
            with redirect_stdout(shown):
                self.assertEqual(main(['show','npc-ripley','--path',str(root)]),0)
            self.assertIn('# Ripley',shown.getvalue())
            backlinks=StringIO()
            with redirect_stdout(backlinks):
                self.assertEqual(main(['backlinks','faction-company','--path',str(root)]),0)
            self.assertIn('npc-ripley\tworks-for\tcurrent',backlinks.getvalue())

    def test_relationship_generation_rejects_parse_errors_without_mutation(self):
        with TemporaryDirectory() as tmp:
            root=Path(tmp)/'campaign';init_campaign(root,name='Test',adapter='mothership')
            npc=create_entity(root,'npc','npc-ripley','Ripley')
            npc.write_text(npc.read_text(encoding='utf-8').replace(
                '## Connections\n', '## Connections\n\n- malformed relationship\n', 1
            ),encoding='utf-8')
            entity_index=root/'00-drydock'/'entity-index.md'
            connection_index=root/'00-drydock'/'connection-index.md'
            entity_index.write_text('existing entity index\n',encoding='utf-8')
            connection_index.write_text('existing connection index\n',encoding='utf-8')
            with self.assertRaisesRegex(SystemExit,'malformed connection'):
                standalone.build_indexes(root)
            self.assertEqual(entity_index.read_text(encoding='utf-8'),'existing entity index\n')
            self.assertEqual(connection_index.read_text(encoding='utf-8'),'existing connection index\n')

    def test_relationship_generation_rejects_dangling_targets_without_mutation(self):
        with TemporaryDirectory() as tmp:
            root=Path(tmp)/'campaign';init_campaign(root,name='Test',adapter='mothership')
            npc=create_entity(root,'npc','npc-ripley','Ripley')
            npc.write_text(npc.read_text(encoding='utf-8').replace(
                '## Connections\n',
                '## Connections\n\n- `works-for` -> [[missing-faction]] (`current`) — Missing target.\n',
                1,
            ),encoding='utf-8')
            entity_index=root/'00-drydock'/'entity-index.md'
            connection_index=root/'00-drydock'/'connection-index.md'
            context=root/'00-drydock'/'ai-context.md'
            entity_index.write_text('existing entity index\n',encoding='utf-8')
            connection_index.write_text('existing connection index\n',encoding='utf-8')
            context.write_text('existing context\n',encoding='utf-8')
            with self.assertRaisesRegex(SystemExit,'target missing-faction does not exist'):
                standalone.build_indexes(root)
            self.assertEqual(entity_index.read_text(encoding='utf-8'),'existing entity index\n')
            self.assertEqual(connection_index.read_text(encoding='utf-8'),'existing connection index\n')
            with self.assertRaisesRegex(SystemExit,'target missing-faction does not exist'):
                main(['context',str(root)])
            self.assertEqual(entity_index.read_text(encoding='utf-8'),'existing entity index\n')
            self.assertEqual(connection_index.read_text(encoding='utf-8'),'existing connection index\n')
            self.assertEqual(context.read_text(encoding='utf-8'),'existing context\n')

    def test_context_unknown_focus_does_not_mutate_generated_files(self):
        with TemporaryDirectory() as tmp:
            root=Path(tmp)/'campaign';init_campaign(root,name='Test',adapter='mothership')
            create_entity(root,'npc','npc-ripley','Ripley')
            standalone.build_indexes(root)
            entity_index=root/'00-drydock'/'entity-index.md'
            connection_index=root/'00-drydock'/'connection-index.md'
            context=root/'00-drydock'/'ai-context.md'
            before=(entity_index.read_bytes(),connection_index.read_bytes(),context.read_bytes())
            with self.assertRaisesRegex(SystemExit,'Unknown entity ID'):
                main(['context',str(root),'--focus','missing-id'])
            after=(entity_index.read_bytes(),connection_index.read_bytes(),context.read_bytes())
            self.assertEqual(after,before)

    def test_duplicate_entity_ids_block_all_graph_retrieval_without_mutation(self):
        with TemporaryDirectory() as tmp:
            root=Path(tmp)/'campaign';init_campaign(root,name='Test',adapter='mothership')
            npc=create_entity(root,'npc','npc-ripley','Ripley')
            duplicate=root/'05-npcs'/'npc-ripley-copy.md'
            duplicate.write_text(npc.read_text(encoding='utf-8'),encoding='utf-8')
            entity_index=root/'00-drydock'/'entity-index.md'
            connection_index=root/'00-drydock'/'connection-index.md'
            context=root/'00-drydock'/'ai-context.md'
            before=(entity_index.read_bytes(),connection_index.read_bytes(),context.read_bytes())
            operations=(
                lambda: standalone.build_indexes(root),
                lambda: main(['context',str(root),'--focus','npc-ripley']),
                lambda: standalone.related_entities(root,'npc-ripley'),
                lambda: standalone.print_backlinks(root,'npc-ripley'),
                lambda: standalone.print_history(root,'npc-ripley'),
            )
            for operation in operations:
                with self.subTest(operation=operation), self.assertRaisesRegex(
                    SystemExit,
                    r'duplicate entity ID npc-ripley: .*npc-ripley-copy\.md and .*npc-ripley\.md',
                ):
                    operation()
            after=(entity_index.read_bytes(),connection_index.read_bytes(),context.read_bytes())
            self.assertEqual(after,before)
            output=StringIO()
            with redirect_stdout(output):
                self.assertEqual(standalone.validate_campaign(root),1)
            self.assertIn('duplicate entity ID npc-ripley',output.getvalue())

    def test_context_rejects_invalid_retrieval_limits(self):
        with TemporaryDirectory() as tmp:
            root=Path(tmp)/'campaign';init_campaign(root,name='Test',adapter='mothership')
            for value in ('0','-1'):
                with self.assertRaises(SystemExit):
                    standalone.main(['context','--max-records',value],root=root)
            with self.assertRaises(SystemExit):
                standalone.main(['context','--depth','-1'],root=root)

    def test_validation_rejects_malformed_connection_configuration(self):
        with TemporaryDirectory() as tmp:
            root=Path(tmp)/'campaign';init_campaign(root,name='Test',adapter='mothership')
            adapter_path=root/'00-drydock'/'adapter.json'
            adapter=json.loads(adapter_path.read_text(encoding='utf-8'))
            adapter['connections']['states']='current'
            adapter['connections']['relationships']=['works-for']
            adapter_path.write_text(json.dumps(adapter),encoding='utf-8')
            output=StringIO()
            with redirect_stdout(output):
                self.assertEqual(standalone.validate_campaign(root),1)
            self.assertIn('connections.states must be a non-empty list of unique kebab-case strings',output.getvalue())
            self.assertIn('connections.relationships must map',output.getvalue())

    def test_validation_rejects_unusable_or_duplicate_connection_states(self):
        for states in (["not usable"],["current","current"]):
            with self.subTest(states=states), TemporaryDirectory() as tmp:
                root=Path(tmp)/'campaign';init_campaign(root,name='Test',adapter='mothership')
                adapter_path=root/'00-drydock'/'adapter.json'
                adapter=json.loads(adapter_path.read_text(encoding='utf-8'))
                adapter['connections']['states']=states
                adapter_path.write_text(json.dumps(adapter),encoding='utf-8')
                output=StringIO()
                with redirect_stdout(output):
                    self.assertEqual(standalone.validate_campaign(root),1)
                self.assertIn('unique kebab-case strings',output.getvalue())

    def test_connection_validation_and_legacy_audit_are_non_destructive(self):
        with TemporaryDirectory() as tmp:
            root=Path(tmp)/'campaign';init_campaign(root,name='Test',adapter='mothership')
            npc=create_entity(root,'npc','npc-ripley','Ripley')
            original=npc.read_text(encoding='utf-8').replace(
                'current_status: unknown', 'current_status: unknown\nfactions: [faction-company]')
            npc.write_text(original.replace(
                '<!-- - `relationship` → [[target-id|Readable Name]] (`current`) — One concise sentence of context. -->',
                '- `works-for` → [[missing-faction]] (`current`) — Explicit but unresolved.'
            ),encoding='utf-8')
            output=StringIO()
            with redirect_stdout(output):
                self.assertEqual(standalone.validate_campaign(root),1)
            self.assertIn('connection target missing-faction does not exist',output.getvalue())
            before=npc.read_text(encoding='utf-8')
            with redirect_stdout(StringIO()):
                self.assertEqual(standalone.audit_connections(root),0)
            self.assertEqual(npc.read_text(encoding='utf-8'),before)

    def test_validation_rejects_unsafe_adapter_entity_paths(self):
        with TemporaryDirectory() as tmp:
            root=Path(tmp)/'campaign';init_campaign(root,name='Test',adapter='mothership')
            path=root/'00-drydock/adapter.json'
            config=json.loads(path.read_text(encoding='utf-8'))
            config['entity_types']['npc']['destination']='../escape/{id}.md'
            path.write_text(json.dumps(config),encoding='utf-8')
            output=StringIO()
            with redirect_stdout(output):
                self.assertEqual(validate_campaign(root),1)
            self.assertIn('npc.destination is unsafe',output.getvalue())

if __name__=='__main__': unittest.main()
