from __future__ import annotations
from pathlib import Path
from datetime import datetime
import argparse, json, re

ROOT=Path(__file__).resolve().parents[1]
VALID={"idea","draft","review","canon","revealed","archived","accepted"}

def fm(text):
    if not text.startswith('---\n'): return {}
    end=text.find('\n---',4)
    if end<0:return {}
    out={}
    for line in text[4:end].splitlines():
        if ':' in line and not line.startswith(' '):
            k,v=line.split(':',1);out[k.strip()]=v.strip().strip('"')
    return out

def validate():
    errors=[];warnings=[];ids={};files=list(ROOT.rglob('*.md'))
    known={p.stem.lower() for p in files}|{p.relative_to(ROOT).with_suffix('').as_posix().lower() for p in files}
    try: json.loads((ROOT/'.drydock.json').read_text(encoding='utf-8'))
    except Exception as exc: errors.append(f'Manifest error: {exc}')
    for p in files:
        text=p.read_text(encoding='utf-8');meta=fm(text);rel=p.relative_to(ROOT)
        if meta.get('status') and meta['status'] not in VALID:errors.append(f'{rel}: invalid status')
        if meta.get('id'):
            if meta['id'] in ids:errors.append(f"{rel}: duplicate id {meta['id']}")
            ids[meta['id']]=rel
        for raw in re.findall(r'\[\[([^\]]+)\]\]',text):
            target=raw.split('|',1)[0].split('#',1)[0].strip().lower()
            if target and target not in known:warnings.append(f'{rel}: unresolved [[{raw}]]')
    print(f'Checked {len(files)} Markdown files.')
    for x in warnings:print('WARNING:',x)
    for x in errors:print('ERROR:',x)
    if not errors:print(f'Validation passed with {len(warnings)} warning(s).')
    return 1 if errors else 0

def body(text):
    if text.startswith('---\n'):
        end=text.find('\n---',4)
        if end>=0:return text[end+4:].strip()
    return text.strip()

def context():
    out=ROOT/'00-drydock'/'ai-context.md';parts=['# AI Context','', '> Generated by Warden Drydock. Do not edit manually.',f"> Generated: {datetime.now().astimezone().isoformat(timespec='seconds')}",'']
    for name in ('current-state.md','canon-policy.md','system-principles.md'):
        p=ROOT/'00-drydock'/name
        if p.exists():parts += [f'## {p.stem.replace("-"," ").title()}','',body(p.read_text(encoding='utf-8')),'']
    logs=sorted((ROOT/'12-sessions'/'logs').glob('*.md'))
    parts += ['## Latest Session','',body(logs[-1].read_text(encoding='utf-8')) if logs else 'No approved session log recorded.','']
    out.write_text('\n'.join(parts).rstrip()+'\n',encoding='utf-8');print(f'Wrote {out.relative_to(ROOT)}');return 0

p=argparse.ArgumentParser();p.add_argument('command',choices=['validate','context']);a=p.parse_args();raise SystemExit(validate() if a.command=='validate' else context())
