services:
  app:
    ports:
      - target: 8080
        published: "8080"
        host_ip: 127.0.0.1
        protocol: tcp
      - target: 8080
        published: "8080"
        host_ip: "::1"
        protocol: tcp
