"""Portable campaign maintenance commands.

This module intentionally uses only the Python standard library. The generator
copies it verbatim into campaign repositories as ``scripts/drydock.py`` while
the framework imports the same implementation.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


VALID_STATUSES = {
    "idea",
    "draft",
    "review",
    "canon",
    "revealed",
    "archived",
    "accepted",
}
APPROVED_SESSION_STATUSES = {"canon", "revealed", "accepted"}


def frontmatter(text: str) -> dict[str, str]:
    if not text.startswith("---\n"):
        return {}
    end = text.find("\n---", 4)
    if end < 0:
        return {}
    result: dict[str, str] = {}
    for line in text[4:end].splitlines():
        if ":" in line and not line.startswith(" "):
            key, value = line.split(":", 1)
            result[key.strip()] = value.strip().strip('"')
    return result


def body(text: str) -> str:
    if text.startswith("---\n"):
        end = text.find("\n---", 4)
        if end >= 0:
            return text[end + 4 :].strip()
    return text.strip()


def validate_campaign(root: Path) -> int:
    root = root.resolve()
    errors: list[str] = []
    warnings: list[str] = []
    ids: dict[str, Path] = {}
    manifest = root / ".drydock.json"
    if not manifest.exists():
        errors.append("Missing .drydock.json")
    else:
        try:
            json.loads(manifest.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            errors.append(f"Invalid .drydock.json: {exc}")

    files = list(root.rglob("*.md"))
    known = {path.stem.lower() for path in files} | {
        path.relative_to(root).with_suffix("").as_posix().lower() for path in files
    }
    for path in files:
        text = path.read_text(encoding="utf-8")
        metadata = frontmatter(text)
        relative = path.relative_to(root)
        status = metadata.get("status")
        if status and status not in VALID_STATUSES:
            errors.append(f"{relative}: invalid status {status}")
        entity_id = metadata.get("id")
        if entity_id:
            if entity_id in ids:
                errors.append(f"{relative}: duplicate ID {entity_id}")
            ids[entity_id] = relative
        for raw in re.findall(r"\[\[([^\]]+)\]\]", text):
            target = raw.split("|", 1)[0].split("#", 1)[0].strip().lower()
            if target and target not in known:
                warnings.append(f"{relative}: unresolved wikilink [[{raw}]]")
        if any(marker in text for marker in ("<<<<<<<", "=======", ">>>>>>>")):
            errors.append(f"{relative}: merge conflict marker")

    print(f"Checked {len(files)} Markdown files.")
    for warning in warnings:
        print("WARNING:", warning)
    for error in errors:
        print("ERROR:", error)
    if errors:
        return 1
    print(f"Validation passed with {len(warnings)} warning(s).")
    return 0


def _approved_session_logs(root: Path) -> list[Path]:
    logs = []
    for path in (root / "12-sessions" / "logs").glob("*.md"):
        metadata = frontmatter(path.read_text(encoding="utf-8"))
        if metadata.get("status") in APPROVED_SESSION_STATUSES:
            logs.append(path)
    return sorted(logs)


def build_context(root: Path) -> Path:
    root = root.resolve()
    output = root / "00-drydock" / "ai-context.md"
    sources = [
        root / "00-drydock" / "current-state.md",
        root / "00-drydock" / "canon-policy.md",
        root / "00-drydock" / "system-principles.md",
    ]
    parts = [
        "# AI Context",
        "",
        "> Generated by Warden Drydock. Do not edit manually.",
        "",
    ]
    for path in sources:
        if path.exists():
            parts += [
                f"## {path.stem.replace('-', ' ').title()}",
                "",
                body(path.read_text(encoding="utf-8")),
                "",
            ]
    logs = _approved_session_logs(root)
    parts += [
        "## Latest Approved Session",
        "",
        body(logs[-1].read_text(encoding="utf-8"))
        if logs
        else "No approved session log recorded.",
        "",
    ]
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(parts).rstrip() + "\n", encoding="utf-8")
    print(f"Wrote {output.relative_to(root)}")
    return output


def main(argv: list[str] | None = None, *, root: Path | None = None) -> int:
    parser = argparse.ArgumentParser(description="Warden Drydock campaign maintenance")
    parser.add_argument("command", choices=["validate", "context"])
    args = parser.parse_args(argv)
    campaign_root = root or Path(__file__).resolve().parents[1]
    if args.command == "validate":
        return validate_campaign(campaign_root)
    build_context(campaign_root)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
