from pathlib import Path
from datetime import datetime


def _body(text: str) -> str:
    if text.startswith("---\n"):
        end = text.find("\n---", 4)
        if end >= 0:
            return text[end + 4 :].strip()
    return text.strip()


def build_context(root: Path) -> Path:
    root = root.resolve()
    output = root / "00-drydock" / "ai-context.md"
    sources = [
        root / "00-drydock" / "current-state.md",
        root / "00-drydock" / "canon-policy.md",
        root / "00-drydock" / "system-principles.md",
    ]
    parts = [
        "# AI Context",
        "",
        "> Generated by Warden Drydock. Do not edit manually.",
        f"> Generated: {datetime.now().astimezone().isoformat(timespec='seconds')}",
        "",
    ]
    for path in sources:
        if path.exists():
            parts += [
                f"## {path.stem.replace('-', ' ').title()}",
                "",
                _body(path.read_text(encoding="utf-8")),
                "",
            ]
    logs = sorted((root / "12-sessions" / "logs").glob("*.md"))
    parts += [
        "## Latest Session",
        "",
        _body(logs[-1].read_text(encoding="utf-8"))
        if logs
        else "No approved session log recorded.",
        "",
    ]
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(parts).rstrip() + "\n", encoding="utf-8")
    print(f"Wrote {output.relative_to(root)}")
    return output
